run:
  timeout: 5m

linters:
  enable-all: true

  disable:
  - cyclop # alternative: gocognit - could add if we start unit testing heavily
  - execinquery # broken: triggers on non-SQL queries
  - exhaustivestruct # deprecated: replaced by exhaustruct
  - exhaustruct  # disagree - also not the intended use
  - funlen # alternative: gocognit
  - gochecknoglobals # impractical
  - godot # disagree
  - godox # disagree
  - golint # deprecated: replaced by revive
  - gomnd # disagree
  - interfacer # deprecated
  - ireturn # disagree
  - lll # impractical
  - maligned # deprecated: replaced by govet
  - nlreturn # disagree
  - nonamedreturns # disagree
  - paralleltest # impractical
  - revive # disagree
  - scopelint # deprecated: replaced by exportloopref
  - testpackage # disagree
  - wrapcheck # disagree
  - wsl # disagree

severity:
  default-severity: error

issues:
  exclude-rules:
  - linters:
    - govet
    text: "composites: `go.mongodb.org/mongo-driver/bson/primitive.E` composite literal uses unkeyed fields"

linters-settings:
  forbidigo:
    forbid:
    - 'errors\.New'
    - 'fmt\.Error.*'
    - 'fmt\.Print.*'
    - 'ioutil\.*'
    - 'pretty\.Print.*'
    - 'reflect\..*'

  govet:
    enable-all: true
    disable:
    - fieldalignment # impractical

  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: true
    require-specific: true

  tagliatelle:
    case:
      rules:
        json: snake

  varnamelen:
    ignore-names:
    - T
    - db
    - fn
    - id
    - ok
    ignore-decls:
    - fs *flag.FlagSet
    - g *errgroup.Group
    - is *is.I
    - sb strings.Builder
    - wg sync.WaitGroup
