run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable-all: true

  disable:
  - cyclop # alternative: gocognit - could add if we start unit testing heavily
  - deadcode # deprecated: replaced by unused
  - depguard # impractical
  - execinquery # broken: triggers on non-SQL queries
  - exhaustivestruct # deprecated: replaced by exhaustruct
  - exhaustruct  # disagree - also not the intended use
  - funlen # alternative: gocognit
  - gochecknoglobals # impractical
  - godot # disagree
  - godox # disagree
  - golint # deprecated: replaced by revive
  - gomnd # disagree
  - ifshort # deprecated
  - inamedparam # disagree
  - interfacer # deprecated
  - ireturn # disagree
  - lll # impractical
  - maligned # deprecated: replaced by govet
  - mnd # disagree
  - nlreturn # disagree
  - nonamedreturns # disagree
  - nosnakecase # deprecated: replaced by revive
  - paralleltest # impractical
  - perfsprint # disagree: code readability matters more
  - protogetter # disagree
  - revive # disagree
  - scopelint # deprecated: replaced by exportloopref
  - structcheck # deprecated: replaced by unused
  - testpackage # disagree
  - varcheck # deprecated: replaced by unused
  - wrapcheck # disagree
  - wsl # disagree

severity:
  default-severity: error

issues:
  exclude-rules:
  - linters:
    - contextcheck
    source: "ctx, opts, func\\(ctx mongo\\.SessionContext\\)"
  - linters:
    - gomoddirectives
    text: "local replacement are not allowed: github.com/wearemojo/mojo-public-go"
  - linters:
    - govet
    text: "composites: `go.mongodb.org/mongo-driver/bson/primitive.E` composite literal uses unkeyed fields"
  - linters:
    - govet
    text: "composites: go.mongodb.org/mongo-driver/bson/primitive.E struct literal uses unkeyed fields"
  - path: lib/crpc # TODO: resolve these
    linters:
    - gocognit
    - nestif

linters-settings:
  forbidigo:
    forbid:
    - 'errors\.New' # use merr
    - 'fmt\.Error.*' # use mlog
    - 'fmt\.Print.*' # nolint for structured stdout logging, otherwise use mlog
    - 'ioutil\.*' # replaced by io
    - 'pretty\.Print.*' # shouldn't be committed
    - 'reflect\.DeepEqual' # use go-cmp

  govet:
    enable-all: true
    disable:
    - fieldalignment # impractical

  grouper:
    import-require-grouping: true

  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: true
    require-specific: true

  tagliatelle:
    case:
      rules:
        json: snake

  varnamelen:
    ignore-names:
    - T
    - db
    - fn
    - id
    - ok
    ignore-decls:
    - fs *flag.FlagSet
    - g *errgroup.Group
    - g errgroup.SettledGroup
    - is *is.I
    - r *http.Request
    - sb strings.Builder
    - w http.ResponseWriter
    - wg sync.WaitGroup
